// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stefanini.JF.Hackathon.Data;

namespace Stefanini.JF.Hackathon.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200106032926_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Stefanini.JF.Hackathon.Models.Avaliador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Matricula");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Avaliadores");
                });

            modelBuilder.Entity("Stefanini.JF.Hackathon.Models.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CidadeId");

                    b.Property<string>("Nome");

                    b.Property<double>("Nota");

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("Stefanini.JF.Hackathon.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidatosAprovados");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("Stefanini.JF.Hackathon.Models.Candidato", b =>
                {
                    b.HasOne("Stefanini.JF.Hackathon.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId");
                });
#pragma warning restore 612, 618
        }
    }
}
